### PR TITLE
feat : Enhanced Navbar UI with proper Palette

### LINKED ISSUE #50: [FEATURE] :IMPROVE THE COLOR CODE AND UI OF NAVBAR
#### **Is your feature request related to a problem? Please describe.**
Currently, the navbar appears to have a bland and outdated color scheme, which does not align with the modern aesthetic standards of the website. I'm often frustrated by how the current color code lacks contrast and appeal, making navigation less intuitive for users. Additionally, the layout and design could be more user-friendly, particularly when viewed on different screen sizes.

#### **Describe the solution you'd like**
I would like to suggest an improvement to the color palette used in the navbar, opting for a modern and visually appealing scheme that enhances readability and complements the rest of the site’s design. The UI should also be updated to include better spacing, clearer typography, and mobile responsiveness. Ensuring that the navbar provides a seamless experience across various devices is crucial. An ideal solution would also involve subtle animations to improve interaction feedback.

#### **Checklist**
- [x] I am contributing under GSSoC-ext
- [x] I am contributing under Hacktoberfest
- [x] I follow the contribution guidelines

### PR DESCRIPTION
**Pull request by laxmanp090404**
### 🛠️ Fixes Issue
Closes #50 

### 👨‍💻 Description
I’ve revamped the color scheme and UI of the navbar to give it a modern, visually appealing look that enhances the user experience. The new design includes:
- A fresh, contrasting color palette that improves readability and visual appeal.
- Better spacing and typography to improve clarity and ease of use.

### 📄 Type of Change
- [x] New feature (non-breaking change which adds functionality)

### 📷 Screenshots/GIFs (if any)

https://github.com/user-attachments/assets/54a557e0-2076-4aad-909f-b9ed80054a81
### ✅ Checklist
- [x] I am a participant of GSSoC-ext.
- [x] I have followed the contribution guidelines of this project.
- [x] I have viewed deployment of my code.
- [x] My changes generate no new warnings.
- [x] I have added documentation to explain my changes.

### 🤝 GSSoC Participation
- [x] This PR is submitted under the GSSoC-ext program.
- [x] I have taken prior approval for this feature/fix.
.

### CODE REVIEW

**Review by divyansh-2005 — CHANGES_REQUESTED** [review]
resolve Conflicting files, and do not remove responsiveness.

**Comment by laxmanp090404** [comment]
@divyansh-2005  I have removed conflicts and ensured responsiveness as assigned.

### Desktop Layout:

https://github.com/user-attachments/assets/b73126dc-caaa-4f7e-ad49-1fdc515a625d

### Mobile Layout:

https://github.com/user-attachments/assets/0944fb3c-fd4a-464a-b44e-09453056143a

**Comment by laxmanp090404** [comment]
@divyansh-2005  Please add gssoc24 ext and hacktoberfest-accepted label.

**Review by divyansh-2005 — APPROVED** [review]

**Comment by divyansh-2005** [comment]
Nice work

**Pull request merged**
