### PR TITLE
[BUG] #8 Replaced new favicon icon relevent to project containt

### LINKED ISSUE #8: [FEATURE]: Favicon icon
**Issue**
There is a default fabicon icon.

**Describe the solution you'd like**
I will design a favicon icon and updated in code base.

### PR DESCRIPTION
**Pull request by Amarjha01**
### 🛠️ Fixes Issue
Closes #8 

### 👨‍💻 Description
- Replaced favicon icon relevent to project containt

### 📄 Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)

### ✅ Checklist
- [ ] I am a participant of GSSoC-ext.
- [ ] I have followed the contribution guidelines of this project.
- [ ] I have viewed deployment of my code.
- [ ] My changes generate no new warnings.

### 🤝 GSSoC Participation
- [ ] This PR is submitted under the GSSoC program.
- [ ] I have taken prior approval for this feature/fix.

### CODE REVIEW

**Comment by Amarjha01** [comment]
@divyansh-2005  Sir please Authorize to deploy for checklist. and please don't close This PR if you don't like favicon please suggest me how it should look like that will give me insight.

**Review by divyansh-2005 — APPROVED** [review]
approved

**Comment by Amarjha01** [comment]
@divyansh-2005 sir can you please change the level from level 1 to level1 or level2 or level3 because point didn't added in leaderboard.

image

**Comment by Amarjha01** [comment]
@divyansh-2005 sir can you please update label from level 3 to level3 because point is not reflected in leaderboard.

**Pull request merged**
