### PR TITLE
Enchance the ui ux of news section #82

### LINKED ISSUE #82: [FEATURE] Redesign this news section its not looking professional
image
assign me want to work on this
**check list**
- [ ✔️] I am contributing under GSSoC-ext
- [✔️ ] I am contributing under hacktoberfest
- [ ✔️] I follow contribution guidlines

### PR DESCRIPTION
**Pull request by Sawan-Kushwah**
### 🛠️ Fixes Issue
Closes #82 

https://github.com/user-attachments/assets/c028aac9-df09-402e-af56-6fca6bc656dd

here i updated the css of news section 
i uses dummy data for development and design purpose now its looking fantastic and better user experience it there 
its having the clean and clear description of news 
Created card clickable as they click on the card they will go to the actual article for more details

### ✅ Checklist
- [ ✔️] I am a participant of GSSoC-ext.
- [✔️ ] I have followed the contribution guidelines of this project.
- [✔️ ] I have viewed deployment of my code.
- [✔️ ] My changes generate no new warnings.
- [✔️ ] I have added documentation to explain my changes.

### 🤝 GSSoC Participation
- [✔️ ] This PR is submitted under the GSSoC program.
- [ ✔️] I have taken prior approval for this feature/fix.

### CODE REVIEW

**Comment by DiwareNamrata23** [comment]
@divyansh-2005

**Comment by Sawan-Kushwah** [comment]
@divyansh-2005 why this PR doesn't get merge? is there any issue

**Comment by DiwareNamrata23** [comment]
@Sawan-Kushwah remove the conflicts and give new design accordingly

**Comment by Sawan-Kushwah** [comment]
@DiwareNamrata23 I have resolved all the conflits ! check it onces if changes requried then tell me

**Comment by Sawan-Kushwah** [comment]
@DiwareNamrata23 its doesn't get merge is there any issue with it?

**Pull request closed without merging**
