### PR TITLE
Added a fully functional blog page with backend

### PR DESCRIPTION
**Pull request by Sawan-Kushwah**
issue #163 

https://github.com/user-attachments/assets/dcd1a2ec-c3a9-48d4-ac09-17d64f82a215

Created a fully functional blog page 
where you can create your blog which will get submited and saved on mongodb database
and also you get your latest saved blog it will give you a real content 
and also comments some of the method for future implementation 
you can remove that delete all function i put it for development purpose
you will all the latest blog here

### 📄 Type of Change
- [✅ ] New feature (non-breaking change which adds functionality)
 
 

 

### ✅ Checklist
- [✅ ] I am a participant of GSSoC-ext.
- [ ✅] I have followed the contribution guidelines of this project.
- [✅ ] I have viewed deployment of my code.
- [✅ ] My changes generate no new warnings.
- [ ✅] I have added documentation to explain my changes.

### 🤝 GSSoC Participation
- [✅ ] This PR is submitted under the GSSoC program.
- [✅ ] I have taken prior approval for this feature/fix.

### CODE REVIEW

**Comment by divyansh-2005** [comment]
@Sawan-Kushwah great work please resolve your conflicts

**Comment by Sawan-Kushwah** [comment]
@divyansh-2005 I have resolve all conflicts good to go for merging

**Comment by Sawan-Kushwah** [comment]
@divyansh-2005 can you merge my PR first before anyone so that it doesn't create more merging conflicts

**Comment by Sawan-Kushwah** [comment]
@divyansh-2005 why it doesn't get merge is it creating some issue?

**Pull request merged**
