### PR TITLE
CHORE:added the content and updated the stylings too

### PR DESCRIPTION
**Pull request by vishesh1525**
### 🛠️ Fixes Issue
Closes #33

### 👨‍💻 Description

- Implemented changes to the existing content, ensuring clarity and accuracy throughout the application.
- Added new styling elements to enhance the overall user interface and improve user experience.

### 📄 Type of Change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (adds or updates related documentation)

### 📷 Screenshots/GIFs (if any)
Screenshot 2024-10-02 181339
Screenshot 2024-10-02 181357
Screenshot 2024-10-02 181441

### ✅ Checklist
- [ ] I am a participant of GSSoC-ext.
- [ ] I have followed the contribution guidelines of this project.
- [ ] I have viewed deployment of my code.
- [ ] My changes generate no new warnings.
- [ ] I have added documentation to explain my changes.

### 🤝 GSSoC Participation
- [ ] This PR is submitted under the GSSoC program.
- [ ] I have taken prior approval for this feature/fix.

### CODE REVIEW

**Comment by divyansh-2005** [comment]
plz link issue

**Comment by vishesh1525** [comment]
> plz link issue

@divyansh-2005 
Can I know what's the reason 
I am new to opensource 
I will figure it out

**Comment by divyansh-2005** [comment]
@vishesh1525
edit issue description and replace <issue_number> with ur issue number
 Closes #<issue_number>

**Comment by vishesh1525** [comment]
@divyansh-2005 
i have edited the issue_number sir

**Pull request merged**
