### PR TITLE
Added dynamic containt to website home page

### LINKED ISSUE #6: Add content to website
**Is your feature request related to a problem? Please describe.**
Currently FinNews has random text change it to legit news content 

**Describe the solution you'd like**
change the content to finance News 

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by Amarjha01**
### 🛠️ Fixes Issue #6 
Closes #6 

### 👨‍💻 Description
Added dynamic Containt to website  which fetches live news . I have applied **gnews API** to fetch live data from various resources.

### 📄 Type of Change
- All latest financial updates
- StartUp Insights
- Daily NewsLetter

### 📷 Screenshots/GIFs (if any)

https://github.com/user-attachments/assets/17cbdd62-dbbf-47a9-bc29-d3d745a41a17

### ✅ Checklist
- [ ] I am a participant of GSSoC-ext.
- [ ] I have followed the contribution guidelines of this project.
- [ ] I have viewed deployment of my code.

### 🤝 GSSoC Participation
- [ ] This PR is submitted under the GSSoC program.

### CODE REVIEW

**Comment by Amarjha01** [comment]
@divyansh-2005  Sir please don't close this PR just for Favicon. I will update the favicon because issue is already assigned to me so I'will update favicon in that issue so for now please accept the favicon. I have designed ready i"ll show you.

**Comment by Amarjha01** [comment]
And it's my humble request you to assign me here also before merge and also add labels like 
**good first issue**
**gssoc-ext**
**hacktoberfest
hacktoberfest-accepted
level 3**

**Comment by divyansh-2005** [comment]
@Amarjha01 check it again as its not working 
image

**Comment by Amarjha01** [comment]
sir did you run backend ?

**Comment by divyansh-2005** [comment]
due to recent pr merge there are some conflicts, can plz resolve them
Sorry for the inconvenience

**Comment by Amarjha01** [comment]
> due to recent pr merge there are some conflicts, can plz resolve them Sorry for the inconvenience

ya sure sir give me some time I'll fix them.

**Comment by Amarjha01** [comment]
done sir conflict is resolved now.

**Comment by Amarjha01** [comment]
@divyansh-2005 sir can you please change the level from level 1 to level3 because point didn't added in leaderboard.

image

**Comment by Amarjha01** [comment]
@divyansh-2005  sir can you please update label from level 3 to level3 because point is not reflected in leaderboard. please sir.

**Pull request merged**
