### PR TITLE
Redesign Footer and added

### PR DESCRIPTION
**Pull request by SuyashSingh01**
### 👨‍💻 Description
- Briefly describe the feature or bug fix you've implemented.
- Highlight any major changes or added functionality.
- Mention how it enhances the project.

### 📄Key Changes:

New Layout:

The footer is now divided into three main sections: Logo & Copyright, Policy Links, and Social Media Icons & Quick Links.
This layout improves clarity and user experience by organizing content into distinct areas.
Updated Styling:

Transitioned from  modular CSS to Tailwindcss for better maintainability and scalability.
Enhanced visual appeal with modern fonts, updated color schemes, and responsive layouts for different screen sizes.
Ensured mobile responsiveness to provide a seamless experience across all devices.
Improved Accessibility:

Added clear focus states for improved keyboard navigation.
Enhanced readability with better color contrast ratios.
New Iconography:

Integrated high-quality social media icons, improving brand engagement opportunities.
Added hover effects to icons for better interactivity.
Code Enhancements:

Followed best practices for clean and readable code.
Optimized image assets for faster load times.
Impact: The redesign not only improves the overall user experience but also brings the footer in line with the site's branding guidelines. This update is part of a broader effort to enhance the site’s UI/UX.

Additional Notes:

No breaking changes introduced.
Tested across multiple devices and screen sizes to ensure responsiveness

### 📷 Screenshots/GIFs (if any)
Screenshot 2024-10-10 
![Screenshot 2024-10-10 064640
064702](https://github.com/user-attachments/assets/9d5c9979-91bb-4075-899d-8b558f9ca5a3)
Screenshot 2024-10-10 064617

### ✅ Checklist
-  I am a participant of GSSoC-ext.
-  I have followed the contribution guidelines of this project.
-  I have viewed deployment of my code.

### 🤝 GSSoC Participation
-This PR is submitted under the GSSoC program.
- I have taken prior approval for this feature/fix.

### CODE REVIEW

**Comment by SuyashSingh01** [comment]
@divyansh-2005  could you please  review  this PR and approve it.

**Comment by SuyashSingh01** [comment]
Hi @divyansh-2005  Review and approve this PR There was some conflict previously which is resolved now .

**Comment by DiwareNamrata23** [comment]
@SuyashSingh01 please resolve the conflicting files

**Comment by SuyashSingh01** [comment]
Hi @DiwareNamrata23   I have resolved the issues review  the PR and approve it .

**Pull request closed without merging**
