### PR TITLE
Enhance Header component with accessibility improvements

### PR DESCRIPTION
**Pull request by RajukrRaja**
🛠️ Fixes Issue
Closes Overlapping Content with Navbar( #113)

👨‍💻 Description
Enhanced Header Component: Improved the accessibility and user interaction features of the Header component in the React application.
Menu Toggle Button: Added aria-expanded and aria-label attributes to the menu toggle button, allowing screen readers to provide more context about the button’s state (open/closed).
Search Functionality: Improved the search input styling and integrated a search icon for better usability.
Mobile Responsiveness: Ensured that the navigation menu is fully functional and visually appealing on mobile devices by utilizing CSS media queries.
Navigation Links: Organized and styled the navigation links for better user experience and to ensure consistency across both desktop and mobile views.
Sign In/Sign Up Button: Styled the "Sign In / Sign Up" button to match the overall design aesthetic of the header.
📄 Type of Change
 Bug fix (non-breaking change which fixes an issue)
 New feature (non-breaking change which adds functionality)
 Breaking change (fix or feature that would cause existing functionality to not work as expected)
 Documentation update (adds or updates related documentation)
📷 Screenshots/GIFs

✅ Checklist
 I am a participant of GSSoC-ext.
 I have followed the contribution guidelines of this project.
 I have viewed deployment of my code and it is functioning correctly.
 My changes generate no new warnings.
 I have added documentation to explain my changes.
🤝 GSSoC Participation
 This PR is submitted under the GSSoC program.
 I have taken prior approval for this feature/fix.

### CODE REVIEW

**Comment by RajukrRaja** [comment]
Please mention my name in contributor list

**Comment by DiwareNamrata23** [comment]
@RajukrRaja please see and resolve the conflicts asap!

**Comment by DiwareNamrata23** [comment]
@divyansh-2005 looking good to merge

**Comment by RajukrRaja** [comment]
all conflict are resolved .please check add as contributor in list

**Comment by RajukrRaja** [comment]
@DiwareNamrata23

**Comment by RajukrRaja** [comment]
Kindly merge

**Review by DiwareNamrata23 — CHANGES_REQUESTED** [review]
remove package-lock.json from outside of frontend

**Comment by RajukrRaja** [comment]
@DiwareNamrata23  please review and merge it

**Pull request closed without merging**
